services:
  jupyter:
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
        USER_NAME: ${USER_NAME:-vscode}
        PROJECT_ROOT: ${PROJECT_ROOT:-/home/${USER_NAME:-vscode}/workspace}
    volumes:
      - ../app/:${PROJECT_ROOT:-/home/${USER_NAME:-vscode}/workspace}
      - ~/.ssh:/home/${USER_NAME:-vscode}/.ssh:ro # 読み取り専用としてssh用の秘密鍵をマウント。
      - ~/.gitconfig:/home/${USER_NAME:-vscode}/.gitconfig
    hostname: dev
    env_file:
      - ../app/.env
    stdin_open: true
    tty: true